
import Head from "next/head";
import Image from "next/image";
import {useState} from 'react'

import axios from "axios";
import useSWR from "swr";
import { format } from "fecha";
import { DateRange } from 'react-date-range';

import { API_KEY } from "../utils/vars";

import styles from "../styles/Home.module.css";
import Loader from "../components/loader";
import Card from "../components/card";

import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file

const fetcher = (url) => axios.get(url).then((res) => res.data);

function GetData(dates) {
  console.log(`https://api.nasa.gov/planetary/apod?start_date=${format(new Date(dates[0].startDate), "YYYY-MM-DD")}&end_date=${format(new Date(dates[0].endDate), "YYYY-MM-DD")}&thumbs=true&api_key=${API_KEY}`)
  const { data, error } = useSWR(
    `https://api.nasa.gov/planetary/apod?start_date=${format(new Date(dates[0].startDate), "YYYY-MM-DD")}&end_date=${format(new Date(dates[0].endDate), "YYYY-MM-DD")}&thumbs=true&api_key=${API_KEY}`,
    fetcher
  );

  return {
    data: data,
    isLoading: !error && !data,
    isError: error,
  };
}

const Data = ({dates}) => {
  const { data, isLoading } = GetData(dates);
  if (isLoading) return <Loader />;
  console.log(data)
  return (
    <div className={styles.grid}>
          {data.map((post, index) => 
            <Card post={post} key={index} />
          )}
        </div>
  )
}

const Home = () => {
  const [dates, setDates] = useState([
    {
      startDate: new Date("2022-01-06"),
      endDate: new Date("2022-01-11"),
      key: 'selection'
    }
  ]);



  console.log(dates)
  console.log(dates[0].startDate)

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopify Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Spacestagram</h1>

        <p className={styles.description}>
          Brought to you by NASA&apos;s cool API
        </p>
        
        <DateRange
          editableDateInputs={true}
          onChange={item => setDates([item.selection])}
          moveRangeOnFirstSelection={false}
          ranges={dates}
          maxDate={new Date()}
        />
        <Data dates={dates}/>
      </main>

      <footer className={styles.footer}>Powered by NASA</footer>
    </div>
  );
};

export default Home;
