
import Head from "next/head";
import Image from "next/image";
import {useState} from 'react'

import axios from "axios";
import useSWR from "swr";
import { format } from "fecha";
import { DateRangePicker } from 'rsuite'

import { API_KEY } from "../utils/vars";

import styles from "../styles/Home.module.css";
import 'rsuite/dist/rsuite.min.css';
import Loader from "../components/loader";
import Card from "../components/card";

const fetcher = (url) => axios.get(url).then((res) => res.data);

function GetData(dates) {
  console.log(`https://api.nasa.gov/planetary/apod?start_date=${format(new Date(dates[0]), "YYYY-MM-DD")}&end_date=${format(new Date(dates[1]), "YYYY-MM-DD")}&api_key=${API_KEY}`)
  const { data, error } = useSWR(
    `https://api.nasa.gov/planetary/apod?start_date=${format(new Date(dates[0]), "YYYY-MM-DD")}&end_date=${format(new Date(dates[1]), "YYYY-MM-DD")}&thumbs=true&api_key=${API_KEY}`,
    fetcher
  );

  return {
    data: data,
    isLoading: !error && !data,
    isError: error,
  };
}

const Data = ({dates}) => {
  const { data, isLoading } = GetData(dates);
  if (isLoading) return <Loader />;
  return (
    <div className={styles.grid}>
          {data.map((post, index) => 
            <Card post={post} key={index} />
          )}
        </div>
  )
}

const Home = () => {
  const [dates, setDates] = useState([new Date('2021-01-01'), new Date('2021-01-03')]);
  

  console.log(format(new Date(dates[1]+1), "YYYY-MM-DD"))
  console.log(format(new Date(dates[1]), "YYYY-MM-DD"))


  

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopify Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Spacestagram</h1>

        <p className={styles.description}>
          Brought to you by NASA&apos;s cool API
        </p>
        <DateRangePicker value={dates} onChange={(range) => setDates(range)}/>
        <Data dates={dates}/>
      </main>

      <footer className={styles.footer}>Powered by NASA</footer>
    </div>
  );
};

export default Home;
